baseURL = "https://manuals.ryanfleck.ca/"
languageCode = "en-us"
# https://gohugo.io/variables/site/#site-variables-list
title = "Manuals"
theme = "RCF-Pure"
pygmentsCodeFences = true
sectionPagesMenu = "main"
pygmentsStyle = "friendly"

# All manuals on this site are available from the root.
[permalinks]
    languages = "/:filename"
    libraries = "/:filename"
    courses = "/:filename"

# https://gohugo.io/variables/site/#the-site-params-variable
[params]
    copyright = "Copyright ©2019 Ryan Fleck"
    author = "Ryan Fleck"
    homepage_banner_title = "Prepare to Learn."
    homepage_banner_lead = "Welcome to my personal manuals."
    site_svg_src = "/icons/brain.svg"
    long_site_title = "Manuals"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[markup.goldmark.renderer]
    unsafe = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
