baseURL = "https://hugo-pure.netlify.com"
languageCode = "en-us"
# https://gohugo.io/variables/site/#site-variables-list
title = "Site Title"
theme = "RCF-Pure"
pygmentsCodeFences = true
pygmentsStyle = "vs"
sectionPagesMenu = "main"

# https://gohugo.io/variables/site/#the-site-params-variable
[params]
    copyright = "Copyright © 2019 Name of Entity"
    author = "Firstname Lastname"
    homepage_banner_title = "Hello."
    homepage_banner_lead = "Title and lead can be modified in config.toml"
    site_svg_src = "/icons/brain.svg"
    long_site_title = "Long Site Title"