baseURL = "https://manuals.ryanfleck.ca/"
languageCode = "en-us"
# https://gohugo.io/variables/site/#site-variables-list
title = "Manuals"
theme = "RCF-Pure"
pygmentsCodeFences = true
pygmentsStyle = "colorful"
sectionPagesMenu = "main"

# https://gohugo.io/variables/site/#the-site-params-variable
[params]
    copyright = "Copyright © 2019 Ryan Fleck"
    author = "Ryan Fleck"
    homepage_banner_title = "Prepare to Learn."
    homepage_banner_lead = "Welcome to my personal collection of notes."
    site_svg_src = "/icons/brain.svg"
    long_site_title = "Manuals"